version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3003:3003"
        volumes:
            - /app/node_modules
            - .:/app